builds:
  - binary: masonry
    main: ./cmd/masonry/masonry.go
    ldflags: -s -w -X github.com/opencontrol/compliance-masonry/version.Version={{.Version}} -X github.com/opencontrol/compliance-masonry/version.Commit={{.Commit}} -X github.com/opencontrol/compliance-masonry/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    format_overrides:
      - goos: windows
        format: zip


  - binary: compliance-masonry
    main: ./cmd/compliance-masonry/compliance-masonry.go
    ldflags: -s -w -X github.com/opencontrol/compliance-masonry/version.Version={{.Version}} -X github.com/opencontrol/compliance-masonry/version.Commit={{.Commit}} -X github.com/opencontrol/compliance-masonry/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archive:
  files:
    - LICENSE.md
    - README.md
  format_overrides:
    - goos: windows
      format: zip


nfpm:
  homepage: https://github.com/opencontrol/compliance-masonry
  license: CC0 1.0
  formats:
    - deb
    - rpm

brew:
  name: compliance-masonry
  github:
    owner: opencontrol
    name: homebrew-compliance-masonry
  commit_author:
    name: OpenControl
    email: dev@open-control.org
  homepage: https://github.com/opencontrol/compliance-masonry
